# Site settings
title: Jason Kalec
email: your-email@domain.com
url: https://kalecjason.github.io
description: "My Portfolio showcasing my various works and projects in different fields such as Game Development as well as Software Development"
keywords: "Game Developmer, Software Developmer, Programmer, Jason Kalec"
skills: "Programmer - Game Developer - Software Developer"
meta_author: Kalec Jason

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: Jason

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ff682b #80B3FF
  primary-rgb: "255,105,45" #"128,179,255"
  secondary: 3c3c3c #FD6E8A
  secondary-dark: 0a0a0a #A2122F

# Footer settings
footer:
  copyright: Jason Kalec
  location: Location
  social: Linkedin & Github
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/kalecj/
  - title: github
    url: https://github.com/kalecjason

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.<br /><a href="https://github.com/jeromelachaud/freelancer-theme/blob/master/LICENCE">License</a><br />Freelancer Theme By <a href="http://jekyllthemes.org/themes/freelancer/">Jekyll</a><br /> Modifications Done by Jason Kalec - 2018'

# Build settings
markdown: kramdown
permalink: pretty
